# Training configuration for Pattern Shape prediction model 
# (part I of NeuralTailor)

# 0.5 * stitch cls loss (focal loss) + 0.005 * stitch ce loss + 5 * panel loss
defaults: 
  - data_wrapper: gcd_datawrapper
  - trainer: trainer
  - experiment: experiment
  - model: aipparel_model
  - _self_


experiment:
  run_name: aipparel


from_start: False
model_max_length: 2100
version: liuhaotian/llava-v1.5-7b
precision: bf16
evaluate: False
conv_type: llava_v1
pre_trained: null
storage_dir: null
hydra:
  run:
    dir: /miele/george/garment/sewformer/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}