defaults:
  - garment_tokenizer: default_gcd_garment_tokenizer

_target_: data.datasets.dataset_mm_benchmark.GarmentCodeMMBenchmark
garment_tokenizer: 
  sf_only: False
  include_template_name: False
  num_tags: 108

root_dir: /miele/timur/garmentcodedata
editing_dir: /mnt/gs/sci-garment/garmentcodedata_editing
caption_dir: /mnt/gs/sci-garment/long-caption-processed
mm_dir: /miele/george/mm_benchmark
# sampling_rate: [0,0,0,0,1]
editing_flip_prob: 0
sampling_rate: [0.3, 0.1, 0.1, 0.4, 0.1] # irrelevant
image_size: 1024
vision_tower: openai/clip-vit-large-patch14 
panel_classification: /home/timur/sewformer-garments/garment-estimator/nn/data_configs/panel_classes.json
body_type: default_body
filtered_data_txt: /home/w4756677/garment/garment_foundation_model/sewformer/SewFormer/assets/data_configs/garmentcodedata_filtered_09142024.txt
data_folders: [
  "garments_5000_0"
]
load_by_dataname: /home/w4756677/garment/garment_foundation_model/sewformer/SewFormer/assets/data_configs/garmentcodedata_list.txt
