defaults:
  - garment_tokenizer: gcd_garment_tokenizer

_target_: data.datasets.gcd_mm_dataset.GCDMM


root_dir: ???
editing_dir: ???
caption_dir: ???
# sampling_rate: [0,0,0,0,1]
editing_flip_prob: 0.5
sampling_rate: [0.3, 0.1, 0.1, 0.4, 0.1]
image_size: 1024
vision_tower: openai/clip-vit-large-patch14 
panel_classification: assets/data_configs/panel_classes_garmentcodedata.json
load_by_dataname: assets/data_configs/garmentcodedata_list.txt